"""Update database schema

Revision ID: 148eda44209f
Revises: ec65e1dadd2b
Create Date: 2024-12-21 04:11:50.768044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148eda44209f'
down_revision = 'ec65e1dadd2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
