"""Update database schema

Revision ID: 3070ebb6cbde
Revises: 891bc93f7570
Create Date: 2024-12-21 04:39:20.959683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3070ebb6cbde'
down_revision = '891bc93f7570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
