
"""empty message

Revision ID: 82718b7aba01
Revises: 
Create Date: 2024-12-16 00:30:45.288466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82718b7aba01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
