"""Update database schema

Revision ID: 891bc93f7570
Revises: 148eda44209f
Create Date: 2024-12-21 04:32:21.724398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891bc93f7570'
down_revision = '148eda44209f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
